version: "3"
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    ports:
      - 10080:8000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgressql/data